apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikiaccessfunction
  labels:
    app: wikiaccess-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wikiaccess-app
  template:
    metadata:
      labels:
        app: wikiaccess-app
    spec:
      containers:
      - name: wikiaccess-app
        image: coenet/wikiaccess:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: 50m
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: wiki-secret
      imagePullSecrets:
      - name: regcred
